name: clarity_app
description: "Clarity — AI-Powered Smart Todo List"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  provider: ^6.1.2
  speech_to_text: ^7.0.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  table_calendar: ^3.2.0
  flutter_local_notifications: ^19.0.0
  record: ^5.2.1
  path_provider: ^2.1.5
  path: ^1.9.1
  file_picker: ^8.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
